image: gitpod/workspace-full

# https://www.gitpod.io/docs/config-ports/
# ports:
# - port: 3000
# onOpen: open-preview

# https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: NPM
    before: |

    init: |
      npm install
    command: |
      npm i -g hardhat-shorthand
      hardhat-completion install
      npm run test

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - JuanBlanco.solidity
    - mhutchie.git-graph
