image: gitpod/workspace-full

# https://www.gitpod.io/docs/config-ports/
# ports:
  # - port: 3000
    # onOpen: open-preview

# https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: NPM
    before: >
      npm install -g truffle
    init: >
      npm install
      gp sync-done npm
    command: >
      npm run dev

  - name: Truffle
    init: gp sync-await npm
    command: truffle develop

vscode:
  extensions:
    - dbaeumer.vscode-eslint
